### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2

### ISSUE THREAD

**Issue by ganto** [ypid/yaml4rst#2]
I'm trying to run `yaml4rst` on the `debops-contrib.roundcube` role. Unfortunately it fails with:
```
$ yaml4rst -e 'ansible_full_role_name=debops-contrib.roundcube' defaults/main.yml -i
Traceback (most recent call last):
  File "/usr/bin/yaml4rst", line 9, in <module>
    load_entry_point('yaml4rst==0.1.6', 'console_scripts', 'yaml4rst')()
  File "/usr/lib/python2.7/site-packages/yaml4rst-0.1.6-py2.7.egg/yaml4rst/cli.py", line 145, in main
    reformatter.reformat()
  File "/usr/lib/python2.7/site-packages/yaml4rst-0.1.6-py2.7.egg/yaml4rst/reformatter.py", line 159, in reformat
    yaml.safe_load(self.get_content())
  File "/usr/lib/python2.7/site-packages/yaml4rst-0.1.6-py2.7.egg/yaml4rst/reformatter.py", line 118, in get_content
    return '\n'.join(self._lines)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 37: ordinal not in range(128)
```

I installed it from git:
```
$ git clone https://github.com/ypid/yaml4rst.git
$ cd yaml4rst
$ sudo python setup.py install
```
```
$ yaml4rst --version
0.1.6
$ python --version
Python 2.7.13
```

**Comment by ganto** [comment]
Running the command in debug mode will output the following context:
```
DEBUG (reformatter.py:799): fold change: 0, line: ---
DEBUG (reformatter.py:799): fold change: 0, line: # .. vim: foldmarker=[[[,]]]:foldmethod=marker
DEBUG (reformatter.py:799): fold change: 0, line: 
DEBUG (reformatter.py:799): fold change: 1, line: # debops-contrib.roundcube default variables [[[
DEBUG (reformatter.py:799): fold change: 0, line: # ==============================================
DEBUG (reformatter.py:799): fold change: 0, line: 
DEBUG (reformatter.py:799): fold change: 0, line: # .. contents:: Sections
DEBUG (reformatter.py:799): fold change: 0, line: #    :local:
DEBUG (reformatter.py:799): fold change: 0, line: #
DEBUG (reformatter.py:799): fold change: 0, line: # .. include:: includes/all.rst
DEBUG (reformatter.py:801): header_fold_unbalance in from _get_rendered_template: 0
DEBUG (reformatter.py:833): self._last_line_fold_yaml_block: False
DEBUG (reformatter.py:302): _get_closing_folds returns: []
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line:   - 'json'
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line:   - 'zip'
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line: roundcube__custom_php_packages: []
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line:   - '{{ [ "sqlite3" ] if (roundcube__database_map[roundcube__database].dbtype == "sqlite") else [] }}'
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line:                                  else [] }}'
DEBUG (reformatter.py:530): Detected 1 closing folds                                                                                                             [68/4753]
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line:                                  else [] }}'
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line: roundcube__packages: []
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line: roundcube__base_packages: [ 'curl', 'file', 'unzip' ]
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line: roundcube__composer_packages: [ 'composer ']
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line:                               else False }}'
DEBUG (reformatter.py:530): Detected 2 closing folds
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line: roundcube__user: 'roundcube'
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line: roundcube__group: 'roundcube'
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line:                        else "/var/local") + "/" + roundcube__user }}'
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line: roundcube__comment: 'Roundcube Webmail'
DEBUG (reformatter.py:530): Detected 2 closing folds
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line: roundcube__git_repo: 'https://github.com/roundcube/roundcubemail.git'
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line: roundcube__git_dest: '{{ roundcube__src + "/" + roundcube__git_repo.split("://")[1] }}'
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line: roundcube__git_version: '1.3.0'
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line:                              "/public" }}'
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line:                       else "/usr/local/src") + "/" + roundcube__user }}'
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line:                     else "/srv/www" }}'
DEBUG (reformatter.py:530): Detected 2 closing folds
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line: roundcube__database: 'sqlite-default'
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line: roundcube__database: 'sqlite-default'
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line: roundcube__database_user: 'roundcube'
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line:                                        + "/" + roundcube__database_user + "/password" }}'
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line: roundcube__database_password: '{{ lookup("password", roundcube__database_password_path + " length=30") }}'
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line: roundcube__database_name: 'roundcubemail'
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line:     dbtableprefix: ''
DEBUG (reformatter.py:530): Detected 2 closing folds
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line: roundcube__domain: [ 'roundcube.{{ ansible_domain }}' ]
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line: roundcube__default_host: 'localhost'
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line: roundcube__smtp_server: ''
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line: roundcube__smtp_port: '25'
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line: roundcube__smtp_user: ''
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line: roundcube__smtp_pass: ''
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line: roundcube__des_key: '{{ lookup("password", secret + "/credentials/" + ansible_fqdn + "/roundcube/des_key chars=hexdigits length=24") }}'
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line: roundcube__local_config_map: {}
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line: roundcube__group_local_config_map: {}
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line: roundcube__host_local_config_map: {}
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line: roundcube__default_plugins: [ 'archive', 'filesystem_attachments', 'jqueryui', 'zipdownload' ]
DEBUG (reformatter.py:530): Detected 2 closing folds
DEBUG (reformatter.py:530): Detected 2 closing folds
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line:     php_upstream: 'php_roundcube'
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line: roundcube__nginx_access_policy: ''
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line:     php_pool: 'roundcube'
DEBUG (reformatter.py:530): Detected 1 closing folds
DEBUG (reformatter.py:534): breaking out of delete empty line loop at line:   - '{{ roundcube__custom_php_packages }}'
DEBUG (reformatter.py:530): Detected 3 closing folds
Traceback (most recent call last):
  File "/usr/bin/yaml4rst", line 9, in <module>
    load_entry_point('yaml4rst==0.1.6', 'console_scripts', 'yaml4rst')()
  File "/usr/lib/python2.7/site-packages/yaml4rst-0.1.6-py2.7.egg/yaml4rst/cli.py", line 145, in main
    reformatter.reformat()
  File "/usr/lib/python2.7/site-packages/yaml4rst-0.1.6-py2.7.egg/yaml4rst/reformatter.py", line 159, in reformat
    yaml.safe_load(self.get_content())
  File "/usr/lib/python2.7/site-packages/yaml4rst-0.1.6-py2.7.egg/yaml4rst/reformatter.py", line 118, in get_content
    return '\n'.join(self._lines)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 37: ordinal not in range(128)
```

**Comment by ypid** [comment]
Issue is known and ignored :) Who uses Python2 today :)

This package/program is only compatiable with Python3 which is mentioned in the readme (badges). All CI tests only run on Python3.

Refs:

* https://github.com/ypid/yaml4rst/blob/master/setup.py
* https://github.com/ypid/yaml4rst/blob/master/.travis.yml

I will add a condition which makes the program terminate on Python2 to make this more obvious.
